repository:
  name: php-contact-form
  description: PHP Contact Form with HTML Emails _DESCRIPTION_ Optional Captcha (Anti-Spam)
  homepage: _HOMEPAGE_
  default_branch: master
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  # - name: first-timers-only
  #   oldname: Help Wanted # Include if renaming
